### ISSUE TITLE
我提个建议

### ISSUE THREAD

**Issue by wulijie** [FinalTeam/RxGalleryFinal#1]
建议：
1：Fragment的形式来提供组件
2：标题toolbar由使用者来导入，不要你写了。
3：默认选择多少条由使用者来设置
4：所有界面按钮的默认颜色都可以设置为统一的颜色--可以让使用者设置。
5：建议界面做的好看点 省的改了。

**Comment by Liar1995** [comment]
Thanks for your suggestion, we'll consider it.

**Comment by fenghebaiyang** [comment]
最好将拍照的按钮放到照片列表的第一个，拍照的按钮在Toolbar太不明显了。

**Comment by Liar1995** [comment]
主要的操作流程和微信的差不多，拍照是默认在第一个的

**Comment by pengjianbo** [comment]
@fenghebaiyang 新版是这样的
