### ISSUE TITLE
Android6.0及以上运行时相机权限问题

### ISSUE THREAD

**Issue by JhonBob** [FinalTeam/RxGalleryFinal#101]

**Comment by JhonBob** [comment]
不手动打开相机权限应用崩溃

**Comment by karl1992** [comment]
1.8

**Comment by JhonBob** [comment]
private void dealXingse(Activity mContext){
        RxGalleryFinal
                .with(mContext)
                .image()
                .crop()
                .radio()
                .imageLoader(ImageLoaderType.GLIDE)
                .subscribe(new RxBusResultSubscriber<ImageRadioResultEvent>() {
                    @Override
                    protected void onEvent(ImageRadioResultEvent imageRadioResultEvent) throws Exception {
                      //省略
                    }
                })
                .openGallery();
    }
当调用上述代码时，在Nexus5x手机上，跳转到相册界面，并弹出运行时权限提示，允许后再点击相机，应用出现错误并退出，到设置里查看应用权限时发现相机权限没有打开，手动打开后，运行正常
