### ISSUE TITLE
最近GitHub下代码速度不好，sample.apk也旧了，不如去掉，精简下文件量。

### ISSUE THREAD

**Issue by NicodeLee** [FinalTeam/RxGalleryFinal#104]
补充：UCrop这个库这边自定义相机还要剪裁，这边自己引用UCrop了，如果去掉使用本库又找不到
com.yalantis.ucrop.UCrop，本库是否考虑引用gradle引用方式而不是引用UCrop代码呢？并且使用.so也增加了体积（UCrop现在有使不使用两种方式）。

**Comment by sheep0704** [comment]
已去，UCrop已去
