### ISSUE TITLE
单选照片存在空指针

### ISSUE THREAD

**Issue by Stevenxin** [FinalTeam/RxGalleryFinal#105]
//3.测试，快速打开单选图片,flag使用true不裁剪
        RxGalleryFinalApi.openRadioSelectImage(_mActivity, new
                RxBusResultSubscriber<ImageRadioResultEvent>() {
            @Override
            protected void onEvent(ImageRadioResultEvent imageRadioResultEvent) throws Exception {

            }
        },true);
暂时使用  RxGalleryFinalApi.getInstance(_mActivity).openRadioSelectImage（...）解决;
![qq 20170410162153](https://cloud.githubusercontent.com/assets/12166318/24852473/316d9420-1e0a-11e7-859e-cd1f9104c8ef.png)
![qq 20170410162358](https://cloud.githubusercontent.com/assets/12166318/24852486/3cbb0e34-1e0a-11e7-94a5-3cfafaf272ef.png)

**Comment by sheep0704** [comment]
tks,GET.

**Comment by sheep0704** [comment]
单选照片存在空指针 #105 ----新版本1.0.3解决，下午发布；
