### ISSUE TITLE
多选图片超过最大值空指针

### ISSUE THREAD

**Issue by 39251474** [FinalTeam/RxGalleryFinal#107]
不添加多选监听时会崩溃
 /**
     * @author KARL-dujinyang
     */
    class OnCheckBoxCheckListener implements CompoundButton.OnCheckedChangeListener{
        private MediaBean mediaBean;

        public OnCheckBoxCheckListener(MediaBean bean){
            this.mediaBean = bean;
        }

        @Override
        public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
            if(mConfiguration.getMaxSize() == mMediaActivity.getCheckedList().size() &&
                    !mMediaActivity.getCheckedList().contains(mediaBean)) {
                AppCompatCheckBox checkBox = (AppCompatCheckBox) buttonView;
                checkBox.setChecked(false);
                Logger.i("选中：" + mMediaActivity.getResources().getString(R.string.gallery_image_max_size_tip, mConfiguration.getMaxSize()));
                iMultiImageCheckedListener.selectedImgMax(buttonView, isChecked, mConfiguration.getMaxSize());
            } else {
                if(iMultiImageCheckedListener!=null)
                    iMultiImageCheckedListener.selectedImg(buttonView, isChecked);
            }

        }
    }

iMultiImageCheckedListener空指针

**Comment by xinyang123123** [comment]
我也遇到了

**Comment by sheep0704** [comment]
GET

**Comment by sheep0704** [comment]
多选图片超过最大值空指针 #107 ---- 新版本1.0.3解决，下午发布；
