### ISSUE TITLE
自定义剪裁比例函数失效

### ISSUE THREAD

**Issue by yuruizhe** [FinalTeam/RxGalleryFinal#114]
版本号为：1.0.2
rxGalleryFinal.cropAspectRatioOptions(0, new AspectRatio("1:1", 1, 1));
这个函数调用无效。
原因如下：
**在MediaGridFragment.radioNext(MediaBean)方法中的传参因未知原因被注释了（LINE:439）
 //AspectRatio []aspectRatios =  mConfiguration.getAspectRatio();
//bundle.putParcelableArrayList(UCrop.Options.EXTRA_ASPECT_RATIO_OPTIONS,arrayList);//EXTRA_CONFIGURATION**
UCropActivity.setupAspectRatioWidget(Intent)方法有正常接收以上参数，但是因为没有传，所以使用默认值

**Comment by sheep0704** [comment]
自定义剪裁比例函数失效----新版本1.0.3解决，下午发布；
