### ISSUE TITLE
Picasso加载的缩略图不是centerCrop模式

### ISSUE THREAD

**Issue by 39251474** [FinalTeam/RxGalleryFinal#115]
缩略图没有保持原比例，Glide显示正常。
Picasso加载图片时有centerCrop()方法可以尝试一下。
目前RxGalleryFinal没有使用自定义实现AbsImageLoader的接口，没办法改动内部实现

**Comment by epolar** [comment]
PicassoImageLoader 中的creator添加centerCrop就好了，希望作者可以添加一下

**Comment by sheep0704** [comment]
Picasso加载的缩略图不是centerCrop模式----新版本1.0.3解决，下午发布；
