### ISSUE TITLE
裁剪回调异常

### ISSUE THREAD

**Issue by YoungDroid** [FinalTeam/RxGalleryFinal#120]
在onResume中调用

RxGalleryFinalApi.cropActivityForResult(UserResponseActivity.this, images -> {
                if ( Debug ) {
                    Log.e( TAG, "onResume - 裁剪后得到的路径： " + images[ 0 ] );
                }
            } );
正常逻辑来说是可以得到裁剪后的路径，但是如果在裁剪的时候选择取消（左上角的X），
这个回调还是能得到相应，结果却是另一个图的路径。

**Comment by sheep0704** [comment]
GET

**Comment by sheep0704** [comment]
try  -- compile 'cn.finalteam.rxgalleryfinal:library:1.0.6'
