### ISSUE TITLE
添加这个包之后与so库存在冲突？与okhttp的也存在冲突

### ISSUE THREAD

**Issue by 1226362423** [FinalTeam/RxGalleryFinal#121]
java.lang.NoClassDefFoundError: okhttp3.internal.tls.OkHostnameVerifier
                                                                      at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:428)

**Comment by 1226362423** [comment]
是不是内部加了OKhttp啊  晕死

**Comment by 1226362423** [comment]
要删除你内部的so的话只能以moudle的形式来使用了吗

**Comment by sheep0704** [comment]
GET

**Comment by sheep0704** [comment]
picasso 默认会使用okhttp，**picasso是选择引用，不需要的话可以不引用。**

**Comment by sheep0704** [comment]
compile 'com.squareup.picasso:picasso:2.5.2'
