### ISSUE TITLE
剪裁回调及图片MediaActivity关闭问题

### ISSUE THREAD

**Issue by yuruizhe** [FinalTeam/RxGalleryFinal#122]
1，图片剪裁完毕后希望可以关闭MediaActivity
2，图片剪裁完毕后的回调是否可以与多图选择的回调统一使用RxBusResultSubscriber.onEvent(T)

**Comment by sheep0704** [comment]
thanks,Get

**Comment by sheep0704** [comment]
晚点请尝试 compile 'cn.finalteam.rxgalleryfinal:library:1.0.5'

**Comment by yuruizhe** [comment]
@sheep0704 感谢

**Comment by Jameshuihui** [comment]
请问一下，这个问题解决了吗

**Comment by sheep0704** [comment]
-- compile 'cn.finalteam.rxgalleryfinal:library:1.0.6'
