### ISSUE TITLE
okhttp3的版本更改

### ISSUE THREAD

**Issue by dongjielitianjiao** [FinalTeam/RxGalleryFinal#124]
我从0.0.9升级到1.0.3 ，咋个okhttp3的的版本也给我变了啊  从3.3.0升级为3.4.1.。。。，好几个类都不见了。。

**Comment by sheep0704** [comment]
嗯 ucrop 自带的 compile 'com.squareup.okhttp3:okhttp:3.4.1'

**Comment by sheep0704** [comment]
如果不需要可exclude module: 'okhttp'
