### ISSUE TITLE
单张选取带裁剪属性返回逻辑问题，选中会弹出裁剪，裁剪完了继续回到选择界面

### ISSUE THREAD

**Issue by jarryleo** [FinalTeam/RxGalleryFinal#126]
单张选取带裁剪属性返回逻辑问题，选中会弹出裁剪，裁剪完了继续回到选择界面，无限循环，这不符合操作逻辑，应该裁剪完后直接返回裁剪后的图片作为选中结果，关闭选择界面！

**Comment by Jameshuihui** [comment]
同问

**Comment by sheep0704** [comment]
thanks，这个在Q群里已GET，因时间忙一直还在修改中

**Comment by sheep0704** [comment]
-- compile 'cn.finalteam.rxgalleryfinal:library:1.0.6'
