### ISSUE TITLE
【裁剪回调】只要activity执行onResume()即会执行onScanCompleted()

### ISSUE THREAD

**Issue by ZengJH** [FinalTeam/RxGalleryFinal#131]
不管是否调用裁剪  是否裁剪  和是否裁剪成功    只要activity onResume()就会执行onScanCompleted()

**Comment by sheep0704** [comment]
刷新检测会调用onScanCompleted，你那边是有业务冲突吗？

**Comment by sheep0704** [comment]
-- compile 'cn.finalteam.rxgalleryfinal:library:1.0.6'
