### ISSUE TITLE
图片选择页面 选择框和完成按钮的颜色怎么换？

### ISSUE THREAD

**Issue by clj12081103** [FinalTeam/RxGalleryFinal#134]
rt

**Comment by 7449** [comment]
暂时不支持，等下个版本吧

**Comment by 7449** [comment]
<style name="Theme_Light.Test">
        <item name="gallery_toolbar_over_button_pressed_color">@color/theme_blue_dark</item>
        <item name="gallery_toolbar_over_button_normal_color">@color/theme_blue_dark</item>
        <item name="gallery_checkbox_button_tint_color">@color/theme_blue_dark</item>
        <item name="gallery_checkbox_text_color">@color/theme_blue_dark</item>
    </style>


这样配置主题，就可以自己配置选择框和完成按钮的颜色，然后在activity页面设置下Theme就可以了

**Comment by clj12081103** [comment]
有效，多谢。
