### ISSUE TITLE
选择完图片后（设置剪切回调的情况），不操作直接返回，就直接崩了

### ISSUE THREAD

**Issue by learnice** [FinalTeam/RxGalleryFinal#135]
System.err: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66547, result=0, data=null} to activity {com.fifedu.dormitorystu/cn.finalteam.rxgalleryfinal.ui.activity.MediaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference

**Comment by liuyu1212120** [comment]
get

**Comment by learnice** [comment]
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == R.id.menu_crop) {
            cropAndSaveImage();
        } else if (item.getItemId() == android.R.id.home) {
            onBackPressed();
        }
        return super.onOptionsItemSelected(item);
    }
这个返回的时候应该做一下处理吧
