### ISSUE TITLE
你好我研读了一下您的源码发现了一个bug

### ISSUE THREAD

**Issue by chenshaoyebj** [FinalTeam/RxGalleryFinal#138]
MediaGridFragment 中设置mConfiguration.isCrop为true的情况下，您并没有根据Config中的aspectRatioX ，aspectRatioY来对UCropActivity做配置 而是直接判断AspectRatio 数组是否为空来决定剪切界面的剪切比例，并且许多参数也没有在这里做相关配置,如是否隐藏底部剪切的控制条,配置压缩率等，希望做下修改,也感谢您的框架对开源事业做的贡献

**Comment by chenshaoyebj** [comment]
以及进入剪裁界面不剪裁图片时返回出现空指针，原因在MediaGridFragment中onActivityResult时Intent为空，而接着调用了onCropFinished 未做非空判断直接从Intent data中获取URI报空指针异常

**Comment by 7449** [comment]
已经fix了 UCrop设置目前只添加了设置toolbar以及statusbar的颜色

**Comment by 7449** [comment]
<attr name="gallery_ucrop_status_bar_color" format="color" />
    <attr name="gallery_ucrop_toolbar_color" format="color" />
    <attr name="gallery_ucrop_toolbar_title" format="string" />
    <attr name="gallery_ucrop_toolbar_widget_color" format="color" />
    <attr name="gallery_ucrop_activity_widget_color" format="color" />

**Comment by chenshaoyebj** [comment]
'cn.finalteam.rxgalleryfinal:library:1.0.6' 可是我在这个版本的库里还是能看到这个错误,是在什么版本fix了我能使用吗

**Comment by 7449** [comment]
下一个版本，等会应该就会放出，稍等，最迟今晚

**Comment by chenshaoyebj** [comment]
好的 谢谢!
