### ISSUE TITLE
不能使用裁切 在选择图片后就已经返回getOriginalPath 裁切后则无任何回调

### ISSUE THREAD

**Issue by ChocolateTan** [FinalTeam/RxGalleryFinal#147]
RxGalleryFinalApi.setImgSaveRxSDCard("cch");
    RxGalleryFinalApi.setImgSaveRxCropSDCard("cch/crop");
    RxGalleryFinal
        .with(this)
        .image()
        .radio()
        .cropAspectRatioOptions(0, new AspectRatio("40:40", 40, 40))
        .crop()
        .imageLoader(ImageLoaderType.FRESCO)
        .subscribe(new RxBusResultSubscriber<ImageRadioResultEvent>() {
          @Override
          protected void onEvent(ImageRadioResultEvent imageRadioResultEvent) throws Exception {
            //图片选择结果
            System.out.println("don "+imageRadioResultEvent.getResult().getOriginalPath());
            System.out.println("don "+imageRadioResultEvent.getResult().getCropPath());
          }
        })
        .openGallery();

**Comment by 7449** [comment]
裁剪的回调是`RxGalleryListener.getInstance().setRadioImageCheckedListener();`

**Comment by tosslife** [comment]
本人也感觉裁剪逻辑设计的也有问题， 既然设置了裁剪那么返回回调里就该有裁剪的图片保存地址
而不是还需要注册另外的监听去监听裁剪完成，返回个Object  逻辑反而多此一举
用过作者之前旧版的类库，感觉新版虽然用了rx但是实用性反倒不如旧版逻辑耐用。
