### ISSUE TITLE
gallery_toolbar_height无效

### ISSUE THREAD

**Issue by Ymmmsick** [FinalTeam/RxGalleryFinal#148]
在style种设置了gallery_toolbar_height属性，高度为48dp,但是toolbar的高度仍然不会变化

**Comment by 7449** [comment]
sample的themes.xml下有个 `Theme_Light.Test`,是注释掉的，里面的属性，都有效果，

**Comment by Ymmmsick** [comment]
我知道有这个，我也试了，确实不行啊。。。

**Comment by 7449** [comment]
你指的裁剪页的toolbar还是?

**Comment by Ymmmsick** [comment]
Meizu M1 Metal,应该和机型没关系的，我设置过30DP也是没有变化，我的设置方式哪里不对么，或者说有其他条件这个才能生效？

**Comment by Ymmmsick** [comment]
相册页

**Comment by 7449** [comment]
有没有在`MediaActivity`下指定对应theme

**Comment by Ymmmsick** [comment]
有的，我的背景和字体都能变化，就是高度变不了

**Comment by Ymmmsick** [comment]
我看你们的代码相册页是可以动态获取，裁剪不可以，但是设置了就是不生效，有点郁闷

**Comment by 7449** [comment]
我在MX5上面试了，有效果

**Comment by Ymmmsick** [comment]
行，那我在看看我这边是不是哪里设置冲突了还是什么

**Comment by 7449** [comment]
en 你再看看，实在搞不定加第二个群找我

**Comment by Ymmmsick** [comment]
好的，感谢
