### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by robotwai** [FinalTeam/RxGalleryFinal#15]
buildToolsVersion "24.0.1"  compileSdkVersion 23
Error:Execution failed for task ':mergeDebugResources'.
>\build\intermediates\exploded-aar\cn.finalteam.rxgalleryfinal\library\0.0.2\res\drawable\gallery_ucrop_vector_loader.xml: Error: Width (0) and height (0) cannot be <= 0
报这样一个错误

**Comment by pengjianbo** [comment]
@robotwai buildToolsVersion "24.0.1" compileSdkVersion 23。请保持版本统一
