### ISSUE TITLE
1.0.4版本在多图选择预览的时候的一个小bug

### ISSUE THREAD

**Issue by finalarcher13** [FinalTeam/RxGalleryFinal#165]
目前使用的是1.0.4的版本，在预览的时候，顶部的计数异常，计数是从0开始的。
我的手机是华为mate8，android版本是6.0。
一个小意见，目前在图片多选的时候，预览按钮是不可隐藏的。从源码上来看是因为使用了this.radio这个标识位作为预览按钮的显示隐藏的根据。就我的理解，一个标识位最好还是不要用作多个用途。所以建议可以增加一个显示隐藏预览按钮的方法。
谢谢

**Comment by finalarcher13** [comment]
不知道在后面与没有修复这个问题，如果在新版本已经修复这个问题，请告知。
PS：目前在Issues里没有看到类似的提问

**Comment by 7449** [comment]
最新的版本号是1.0.9

        if (radio){
            //单选  不显示预览以及顶部完成按钮
        }else{
            //多选  显示预览以及顶部完成按钮
        }

**Comment by finalarcher13** [comment]
你好，你的回答没有解决我的提问。可能是我描述不清楚。
首先我的问题是有个bug，在多选的情况下，当你选择几张图片，进入预览的时候，计数显示0/X，但应该是从1开始显示（比如1/X）。这个问题是1.0.4版本发现的。在最新的1.0.9版本是否有修复？
其次，我个人的建议是现在从源码上来看，预览按钮是和多选单选状态绑定了，能否在多选的情况下隐藏预览按钮？

**Comment by 7449** [comment]
第一个已经修复，第二个  目前多选就有预览按钮，没有隐藏按钮
