### ISSUE TITLE
Android6.0以上拍照闪退

### ISSUE THREAD

**Issue by IdyllicFish** [FinalTeam/RxGalleryFinal#167]
貌似是因为拍照没有动态申请拍照的权限
希望能够修复 不然只能在需打开相册之前就手动申请相机权限

**Comment by sheep0704** [comment]
日志

**Comment by IdyllicFish** [comment]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:file:///storage/emulated/0/DCIM/IMMQY/IMG_20170721172000.jpg} (has extras) } from ProcessRecord{fe2781c 3200:com.zhixin.partyconstructionwebapp/u0a131} (pid=3200, uid=10131) with revoked permission android.permission.CAMERA

**Comment by IdyllicFish** [comment]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:file:///storage/emulated/0/DCIM/IMMQY/IMG_20170721172000.jpg} (has extras) } from ProcessRecord{fe2781c 3200:com.zhixin.partyconstructionwebapp/u0a131} (pid=3200, uid=10131) with revoked permission android.permission.CAMERA

**Comment by 7449** [comment]
你有没有在你的 Androidmanifest.xml 下 申请 android.permission.CAMERA，Library的 Androidmanifest 什么都没有写，还是建议在使用之前就申请到所有的权限，我这边会在处理下 点击 拍照的权限问题

**Comment by IdyllicFish** [comment]
写了，并没有什么用，我必须在代码里面动态申请才不会闪退

原始邮件
发件人:@notifications@github.com
收件人:FinalTeam/RxGalleryFinalRxGalleryFinal@noreply.github.com
抄送:IdyllicFish593353831@qq.com; Authorauthor@noreply.github.com
发送时间:2017年7月23日(周日) 22:17
主题:Re: [FinalTeam/RxGalleryFinal] Android6.0以上拍照闪退 (#167)


你有没有在你的 Androidmanifest.xml 下 申请 android.permission.CAMERA，Library的 Androidmanifest 什么都没有写，还是建议在使用之前就申请到所有的权限，我这边会在处理下 点击 拍照的权限问题

**Comment by 7449** [comment]
我刚才看了下  ，代码中没有对camera权限做处理，我稍后会处理下，sample取巧了.

**Comment by IdyllicFish** [comment]
谢谢
辛苦了😊


原始邮件
发件人:@notifications@github.com
收件人:FinalTeam/RxGalleryFinalRxGalleryFinal@noreply.github.com
抄送:IdyllicFish593353831@qq.com; Authorauthor@noreply.github.com
发送时间:2017年7月23日(周日) 23:03
主题:Re: [FinalTeam/RxGalleryFinal] Android6.0以上拍照闪退 (#167)


我刚才看了下 ，代码中没有对camera权限做处理，我稍后会处理下，sample取巧了.

**Comment by sheep0704** [comment]
FIX
