### ISSUE TITLE
多选，怎么选中上次选中的图片

### ISSUE THREAD

**Issue by 501956430** [FinalTeam/RxGalleryFinal#170]
多选，怎么选中上次选中的图片

**Comment by 501956430** [comment]
设置了selected，图片还是未选中

**Comment by 501956430** [comment]
现在设置了selected，图片可以选中。
有个新问题，计算图片数只会在图片被点击时才计算，希望在每次startActivity图片列表时都执行mCheckedList.size() > 0 计算图片数，否则就显示 “完成”

**Comment by sheep0704** [comment]
FIX
