### ISSUE TITLE
能不能直接打开相机？

### ISSUE THREAD

**Issue by Lightning627** [FinalTeam/RxGalleryFinal#180]
拍完之后最好有个预览的界面

**Comment by 7449** [comment]
please download sample to run ， have the answers you want

**Comment by Lightning627** [comment]
@7449 
When running to....
`RxGalleryFinalApi.getInstance(MaterialRepairActivity.this).openZKCameraForResult(MaterialRepairActivity.this, new MediaScanner.ScanCallback()`

` java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference.`
Android 7.1 of Sony Z5

**Comment by 7449** [comment]
close issues
