### ISSUE TITLE
压缩图片逻辑有问题

### ISSUE THREAD

**Issue by zlkevinet** [FinalTeam/RxGalleryFinal#181]
MediaGridAdapter.onBindViewHolder(),114行：
![image](https://user-images.githubusercontent.com/1165055/29210803-f6c2bc50-7ec7-11e7-9663-9a7830c97500.png)

ImageThumbnailJob.onRunJob(),31行
![image](https://user-images.githubusercontent.com/1165055/29210791-e04e22ca-7ec7-11e7-9614-876e31fe38e1.png)

**Comment by sheep0704** [comment]
GET
