### ISSUE TITLE
use different Glide version

### ISSUE THREAD

**Issue by sunhangwang** [FinalTeam/RxGalleryFinal#189]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager;

how can i use custom ImageLoader

**Comment by 7449** [comment]
无法自定义你自己的ImageLoder,只能通过 `imageLoader ` 指定该框架使用何种图片加载器加载图片

**Comment by DarrenWorks** [comment]
> 无法自定义你自己的ImageLoder,只能通过 `imageLoader ` 指定该框架使用何种图片加载器加载图片

作者你好，此问题是RxGalleryFinal与项目中引用不同版本Glide造成冲突导致的，我使用其他图片加载器避免了此问题，还是希望作者能够找到更好的兼容办法。

**Comment by 9alsacelost** [comment]
这个问题就是你只做了3.x上glide的支持，4.0上glide用法是先要asBtimap等等，才能用load方法
