### ISSUE TITLE
fragment中调用拍照后无法调起裁剪

### ISSUE THREAD

**Issue by YanxuLi** [FinalTeam/RxGalleryFinal#191]
在fragment中调用openZKCamera拍照，fragment中重写的onActivityResult没有调起，请问有什么解决办法吗？原因应该是openZKCamera的构造传了Activity吧

**Comment by 7449** [comment]
想在 fragment 里面生效，需要 fragment.startActivityForResult  ，这里直接用的 activity，你可以直接在你的 fragement 依赖的 activity里面  获取回调

**Comment by sheep0704** [comment]
compile 'cn.finalteam.rxgalleryfinal:library:1.1.3'
