### ISSUE TITLE
怎么设置隐藏 拍摄照片和录制视频？

### ISSUE THREAD

**Issue by qdiankun** [FinalTeam/RxGalleryFinal#195]
感谢源码分享，想问下通过什么设置 去隐藏拍摄照片和录制视频？我只想显示图片选择和视频选择，无需用户拍照和录视频。

**Comment by fcoral** [comment]
hideCamera

**Comment by qdiankun** [comment]
@fcoral thanks，解决了。最好可以在RxGalleryFinalApi封装一个公共的hideCamera方法，不然只能通过修改源码来隐藏
