### ISSUE TITLE
怎么设置默认打开后置摄像头

### ISSUE THREAD

**Issue by dreamlivemeng** [FinalTeam/RxGalleryFinal#197]
RxGalleryFinalApi.openZKCamera（）大神，我调用这个方法默认打开的是前置摄像头，怎么设置为默认打开后置摄像头呀

**Comment by sheep0704** [comment]
这是调取系统，你可以打开之前查看下相机是否为前置摄像头

**Comment by dreamlivemeng** [comment]
额，判断如果为前置摄像头该怎么切换为后置摄像头呢？调取系统方法opencamera(0)参数传0或者1，这个参数怎么传递呢？

**Comment by sheep0704** [comment]
可以加入这个方法去判断：

**Comment by sheep0704** [comment]
private static boolean checkCameraFacing(final int facing) {
    if (getSdkVersion() < Build.VERSION_CODES.GINGERBREAD) {
        return false;
    }
    final int cameraCount = Camera.getNumberOfCameras();
    CameraInfo info = new CameraInfo();
    for (int i = 0; i < cameraCount; i++) {
        Camera.getCameraInfo(i, info);
        if (facing == info.facing) {
            return true;
        }
    }
    return false;
}

public static boolean hasBackFacingCamera() {
    final int CAMERA_FACING_BACK = 0;
    return checkCameraFacing(CAMERA_FACING_BACK);
}
public static boolean hasFrontFacingCamera() {
    final int CAMERA_FACING_BACK = 1;
    return checkCameraFacing(CAMERA_FACING_BACK);
}
public static int getSdkVersion() {
    return android.os.Build.VERSION.SDK_INT;
}
