### ISSUE TITLE
提个图片加载库的建议

### ISSUE THREAD

**Issue by bingoogolapple** [FinalTeam/RxGalleryFinal#2]
可以通过反射来判断当前开发者是否依赖的某个图片加载库，减少开发者集成难度

[BGAImage](https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/library/src/main/java/cn/bingoogolapple/photopicker/imageloader/BGAImage.java)

在library的build.gradle文件里把compile改成provided

[build.gradle](https://github.com/bingoogolapple/BGAPhotoPicker-Android/blob/master/library/build.gradle)

**Comment by w0080626** [comment]
感谢您的建议！

**Comment by pengjianbo** [comment]
@bingoogolapple 谢谢大神的意见。叼叼的。

**Comment by bingoogolapple** [comment]
我不是大神🙂互相学习
