### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: uk/co/senab/photoview/Compat.class

### ISSUE THREAD

**Issue by TurnTears** [FinalTeam/RxGalleryFinal#202]
![image](https://user-images.githubusercontent.com/9336516/30584609-dceaa19a-9d5c-11e7-8172-343cd68ea235.png)

我自己的项目依赖了 compile 'com.github.chrisbanes:PhotoView:2.1.3'，这个怎么破啊？

**Comment by sheep0704** [comment]
photoView冲突，exclude module: 或者移除PhotoView的引用。
