### ISSUE TITLE
华为P10下默认全部照片目录其实没有几张照片

### ISSUE THREAD

**Issue by zhangbaoliang** [FinalTeam/RxGalleryFinal#205]
华为P10下默认全部照片目录其实没有几张照片，反而在相机文件夹下是全部照片，有没有接口设置可以默认选择相机
![qq 20170920200942](https://user-images.githubusercontent.com/2337187/30642981-b41b04ce-9e3f-11e7-9904-9d6e7c1ad8e5.jpg)
![qq 20170920200958](https://user-images.githubusercontent.com/2337187/30642982-b41efe44-9e3f-11e7-8b5c-c79d88d2397b.jpg)

**Comment by sheep0704** [comment]
目前没有这个接口，默认是显示所有，可以自己更改index的默认选中 ，后期会考虑加入这个功能。

**Comment by wpq2014** [comment]
这个所有图片的功能很重要的啊，我看了其他一些库都是有的，希望赶快加上吧，我现在需求用到了选视频所以选择用RxGalleryFinal，所有图片的功能只能我自己改源码了。。

**Comment by keepgoodfeeling** [comment]
8848 android 4.4.4也是这样的问题.所有图片选项展示的只是很少几张图片.并非是所有的图片.

**Comment by TigerZhag** [comment]
@keepgoodfeeling 你好，请问你的这个问题解决了吗

**Comment by zone-yan** [comment]
现在华为meta 20 X还是有这个问题，这个解决了吗
