### ISSUE TITLE
uk.co.senab.photoview 冲突

### ISSUE THREAD

**Issue by proud2008** [FinalTeam/RxGalleryFinal#212]
非常感谢你的项目，帮了很大的忙
uk.co.senab.photoview 是从“com.github.chrisbanes.photoview”这个项目https://github.com/chrisbanes/PhotoView 中 copy的吗？能否用gradle 引入，这样不至于有项目引入photoview中冲突，谢谢

**Comment by sheep0704** [comment]
GET，团队后期会考虑更改，近期可能没时间作出修改。
