### ISSUE TITLE
 merger failed. Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-2

### ISSUE THREAD

**Issue by sheep0704** [FinalTeam/RxGalleryFinal#214]
merger failed.
Suggestion: add 'tools:replace="android:value"' to 
<meta-data> element at AndroidManifest.xml:25:……

解决：
在app的build.gradle中添加如下代码即可搞定：
/*
* 这段代码的意思是强制改变所有引用com.android.support 版本为25.3.0。
* */
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}

可以添加 android{} 中……

**Comment by sheep0704** [comment]
参考。

**Comment by weichenxu1234** [comment]
之前头疼了很久这个问题,苦苦查了好几天,在build.gradle 引入依赖的时候 去除exifinterface 然后自己添加依赖.
/*选择相册图片 视频 三方控件RxGalleryFinal*/
    compile('cn.finalteam.rxgalleryfinal:library:1.1.3') {
        exclude module: 'exifinterface'
    }
    compile "com.android.support:exifinterface:25.1.0"

**Comment by sheep0704** [comment]
这种方法也可以。
