### ISSUE TITLE
无法取消库的依赖

### ISSUE THREAD

**Issue by jeesezh** [FinalTeam/RxGalleryFinal#223]
![image](https://user-images.githubusercontent.com/19542480/32367184-341c6e8a-c0bc-11e7-974d-f6996f3ad78d.png)
当取消依赖的时候就会报这个错,目前已尝试的方法：
1.clean--->build
2.删除build文件夹
3.删除C盘中的.gradle
仍然无法去除这个错误

**Comment by sheep0704** [comment]
全局搜索这个资源文件 ，目测是报了合并资源错误，所以应该是编译合并的时候，找相关资源或代码是否在调用
