### ISSUE TITLE
在Android Studio 3.0上面根本编译不过

### ISSUE THREAD

**Issue by qq296216078** [FinalTeam/RxGalleryFinal#235]
作者快点升级一下as3.0吧，改一下编译的bug，搞了半天了各种错

**Comment by 7449** [comment]
项目的gradle版本号过低,如果你第一次进项目,会提示你是否升级gradle版本,如果你没有升级版本号，你clone下来应该是2.1.3,那么可以成功运行

        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.5.0'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7'


如果你将版本号升级到了3.x，那么请复制以下代码覆盖`project`下面`build.gradle`里面的相同代码

        classpath 'com.android.tools.build:gradle:3.0.1'
     //        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.8.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.0'

然后去掉其他gradle文件里面的`apply plugin: 'me.tatarka.retrolambda`

并且在你的`gradle.properties`文件里面添加`android.enableD8=true`

运行的时候会出现两条`warn`警告，可以忽略,是版本号引起的，但是整个项目是可以成功运行的
