### ISSUE TITLE
和Ucrop冲突

### ISSUE THREAD

**Issue by bravecat** [FinalTeam/RxGalleryFinal#24]
如果已经引入Ucrop，编译时出现如下错误: Multiple dex files define Lcom/yalantis/ucrop/view/TransformImageView

**Comment by Tobecomebest** [comment]
你是不是重复引用了？

**Comment by bravecat** [comment]
是的，已经引用了 compile 'com.yalantis:ucrop:2.1.2。项目需要import类：
https://github.com/Yalantis/uCrop/blob/master/ucrop/src/main/java/com/yalantis/ucrop/UCrop.java，而本项目没有这个类，所以不好取消引用。

**Comment by pengjianbo** [comment]
嗷~，是会引起冲突。

**Comment by sheep0704** [comment]
compile 'cn.finalteam.rxgalleryfinal:library:1.0.1'
