### ISSUE TITLE
UI界面问题

### ISSUE THREAD

**Issue by tianqing2117** [FinalTeam/RxGalleryFinal#25]
如果不需要头像取景框下面，那么强大的功能。我该怎么去除那些呢？我只需要圆形和方形。类似微博那种简洁的界面。

**Comment by pengjianbo** [comment]
你说的是裁剪页底部的控制区域吗？如果是可以通过cropHideBottomControls(true)方法将其隐藏。

**Comment by tianqing2117** [comment]
这个只能禁用 但是没有隐藏呀

**Comment by pengjianbo** [comment]
恩~当前版本是这样的
