### ISSUE TITLE
photoview冲突

### ISSUE THREAD

**Issue by kzqsky** [FinalTeam/RxGalleryFinal#28]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Luk/co/senab/photoview/Compat;

**Comment by pengjianbo** [comment]
请移除掉其他photoview引用

**Comment by ljhUncle** [comment]
如果不是自己使用的依赖，是别的第三方用的photoview依赖，这个怎么办呢？

**Comment by sunyz2016** [comment]
你好 请问你解决了吗？我也遇到了这问题 。谢谢

**Comment by NicodeLee** [comment]
@kzqsky @ljhUncle @sunyz2016 这样添加  compile ('cn.finalteam.rxgalleryfinal:library:0.0.9'){
    exclude group:'Luk/co/senab/photoview/Compat'
  }
