### ISSUE TITLE
有没有提供6.0被拒绝权限的接口或者直接Toast一下提醒也是可以得

### ISSUE THREAD

**Issue by 7449** [FinalTeam/RxGalleryFinal#29]

**Comment by ChineseLincoln** [comment]
Rx的结合RxPermissions做就可以吧？

**Comment by ysn003** [comment]
同样遇到 这个问题，小米5，android 6.0系统的，就是打开相机就挂了

**Comment by 7449** [comment]
@ChineseLincoln 如果框架没有处理啊权限那可以用RxPermission之类的自己处理，但是这个框架已经自己处理了  你再用其他的多此一举

**Comment by ChineseLincoln** [comment]
单一职责，这个库本身只是一个选择图片用的。
增加权限个人觉得没必要，更何况Rx本身可以使用操作符关联在一起使用。

**Comment by 7449** [comment]
你不仅没读过源码 而且没在6.0及6.0以上的模拟器或者真机测试过

**Comment by ChineseLincoln** [comment]
好吧，大神……膜拜一下……
