### ISSUE TITLE
OppoR17进不了相册页面

### ISSUE THREAD

**Issue by 17771436337** [FinalTeam/RxGalleryFinal#310]
在部分oppo R17手机上出现了无法进入对应的相册页面，进入就崩溃

**Comment by liangxiwei** [comment]
大哥，你好歹发一下logcat的日志啊。。。

**Comment by 17771436337** [comment]
额，那个已经好了，是我公司的网络问题，抱歉了哈





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FinalTeam/RxGalleryFinal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月24日(星期四) 下午4:51
收件人:&nbsp;"FinalTeam/RxGalleryFinal"<RxGalleryFinal@noreply.github.com&gt;;
抄送:&nbsp;"蔡名雨"<1020233514@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FinalTeam/RxGalleryFinal] OppoR17进不了相册页面 (#310)





 
大哥，你好歹发一下logcat的日志啊。。。

**Comment by liangxiwei** [comment]
老哥，解决了你主动点closed啊

**Comment by 17771436337** [comment]
抱歉了哈
