### ISSUE TITLE
调用裁剪功能裁剪了图片根本没有效果

### ISSUE THREAD

**Issue by yinyiliang** [FinalTeam/RxGalleryFinal#45]
虽然说是可以选择裁剪  其实感觉只是改变了裁剪框的形状，实际上裁剪过后取到的还是原图。以及在手机上也看不到裁剪后的图片。（调用系统的图片裁剪后，都是能在本地找到被裁剪过的照片的）

**Comment by TestSmirk** [comment]
@yinyiliang 你试试这个方法.

**Comment by yinyiliang** [comment]
虽然我已经换掉不用了，但是还是感谢回复我的问题。

**Comment by TestSmirk** [comment]
不谢🤗
