### ISSUE TITLE
怎么样才能自定义ImageLoader

### ISSUE THREAD

**Issue by nicectrl** [FinalTeam/RxGalleryFinal#49]
如题，看源码貌似只能在四种里面选择？不能用自己的ImageLoader？

**Comment by JeckChou** [comment]
感觉作者已经放弃了他的孩子，完全没有再维护的意思

**Comment by Liar1995** [comment]
[自定义ImageLoader你可以看这里](https://github.com/pengjianbo/GalleryFinal/blob/master/README.md)
@nicectrl

**Comment by sheep0704** [comment]
传入自定义即可
