### ISSUE TITLE
 java.lang.SecurityException: Permission Denial: 相机没做做动态权限么？

### ISSUE THREAD

**Issue by 836154942** [FinalTeam/RxGalleryFinal#59]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 mCallingUid=10177 cmp=com.android.camera2/com.android.camera.ImageCapture clip={text/uri-list U:file:///storage/emulated/0/DCIM/RxGalleryFinal/IMG_20161125202651.jpg} (has extras) } from ProcessRecord{2284bb 32410:com.hahaart.www.app/u0a177, isShadow:false} (pid=32410, uid=10177) with revoked permission android.permission.CAMERA

**Comment by proud2008** [comment]
1.0.4的版本还有这个问题，小米手机3.0

**Comment by xiongyufeng12306** [comment]
解决了没？解决了麻烦大神给我个思路。
