### ISSUE TITLE
怎么在选择好图片后设置宽和高？

### ISSUE THREAD

**Issue by wc520** [FinalTeam/RxGalleryFinal#71]
怎么在选择好图片后设置宽和高？  不剪裁照片，很急，谢谢

**Comment by wc520** [comment]
我找到了  
 imageRadioResultEvent.getResult().setWidth(100);
 imageRadioResultEvent.getResult().setHeight(100);

**Comment by sheep0704** [comment]
imageRadioResultEvent.getResult().setWidth(100);
