### ISSUE TITLE
你好比较急。怎么只裁剪。库里修改了ucrop的库裁剪

### ISSUE THREAD

**Issue by 836154942** [FinalTeam/RxGalleryFinal#74]
怎么只开启裁剪，ucrop库的一些改动没法使ucrop裁剪了。怎么只调用裁剪？移植他的库又重复。打包通不过。

**Comment by yqyzxd** [comment]
解决了吗，哥们

**Comment by 836154942** [comment]
没有解决。不用这了最后

**Comment by sheep0704** [comment]
compile 'cn.finalteam.rxgalleryfinal:library:1.0.1'
