### ISSUE TITLE
 README.md 里的demo 有bug

### ISSUE THREAD

**Issue by tianshaokai** [FinalTeam/RxGalleryFinal#9]
![image](https://cloud.githubusercontent.com/assets/6706496/17122919/4ee3f4ae-5312-11e6-8ec5-29df4b2324fb.png)

**Comment by pengjianbo** [comment]
谢谢~已修复。

**Comment by tianshaokai** [comment]
@pengjianbo  似乎没有修复，我下载了还是有问题

**Comment by pengjianbo** [comment]
@tianshaokai 你好，请下载demo apk试下，是否会报错？

**Comment by tianshaokai** [comment]
我就是安装的README.md 的那个链接apk

**Comment by tianshaokai** [comment]
@pengjianbo 我的测试机 华为荣耀6 plus

**Comment by tianshaokai** [comment]
@pengjianbo  小米手机上demo 可以查看图片了, 不过在预览图片时，图片有点虚了
