### ISSUE TITLE
我调用系统相机拍照返回照片的uri。该用哪个api对这张照片进行裁剪

### ISSUE THREAD

**Issue by yqyzxd** [FinalTeam/RxGalleryFinal#93]
我调用系统相机拍照返回照片的uri。该用哪个api对这张照片进行裁剪

**Comment by dongjielitianjiao** [comment]
最新的提供了直接打开摄像机的api  但是好像没有裁剪功能，返回结果还要自己写裁剪啊。。

**Comment by sheep0704** [comment]
compile 'cn.finalteam.rxgalleryfinal:library:1.0.1'
可以直接裁剪，UCROP更新到2.2
